// Articles ajoutés manuellement côté moverz.fr (hors génération CSV)
import type { BlogPostMeta } from "./blog";

export const BLOG_EXTRA: BlogPostMeta[] = [
  {
    slug: "eviter-arnaques-demenagement",
    title: "Comment éviter les arnaques au déménagement en 2026 : Guide complet",
    description:
      "64% des déménageurs présentent des anomalies (DGCCRF 2023). Découvrez comment vérifier un déménageur, les signaux d'alerte, et les outils pour choisir en toute sécurité.",
    publishedAt: "2025-12-24T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 15,
    authorSlug: "lucie",
  },
  {
    slug: "prix-demenagement-longue-distance-france",
    title: "Prix déménagement longue distance France 2026 : fourchettes réalistes & conseils",
    description:
      "Combien coûte un déménagement longue distance en France en 2026 ? Fourchettes par volume, exemples chiffrés (Paris-Marseille, Lyon-Bordeaux, Lille-Lyon), facteurs de variation et conseils pour comparer.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    updatedAt: "2026-03-07T00:00:00.000Z",
    category: "prix-et-devis",
    readingTimeMinutes: 12,
    tags: ["prix déménagement", "longue distance", "déménagement France", "devis déménagement"],
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-international-juste-prix-experience",
    title: "Déménagement international : dans quels cas Moverz peut vous aider (et comment trouver le juste prix)",
    description:
      "Vous partez ou revenez de l’étranger ? Découvrez dans quels cas Moverz peut vous accompagner pour un déménagement international, comment éviter les mauvaises surprises et trouver le juste prix pour votre projet.",
    publishedAt: "2025-01-02T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 9,
    authorSlug: "guillaume",
  },
  {
    slug: "prix-demenagement-lyon-guide-complet",
    title: "Prix déménagement Lyon 2026 : fourchettes, exemples & conseils",
    description:
      "Combien coûte un déménagement à Lyon en 2026 ? Fourchettes par surface, exemples par quartier, facteurs de variation et conseils pour obtenir des devis comparables sans mauvaises surprises.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    updatedAt: "2026-03-07T00:00:00.000Z",
    category: "prix-et-devis",
    citySlug: "lyon",
    readingTimeMinutes: 12,
    tags: ["prix déménagement Lyon", "déménagement Lyon", "devis déménagement Lyon"],
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-sans-ascenseur-5e-etage",
    title: "Déménagement sans ascenseur au 5e étage : méthode, devis fiable & checklist",
    description:
      "Surcoût escalier, monte-meuble ou portage, checklist anti-surprise : tout ce qu'il faut savoir pour déménager sans ascenseur au 5e étage sans mauvaise surprise.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    updatedAt: "2026-03-07T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 10,
    tags: ["déménagement sans ascenseur", "surcoût escalier", "monte-meuble", "5e étage"],
    authorSlug: "guillaume",
  },
  {
    slug: "portage-long-camion-loin-entree",
    title: "Portage long : camion loin de l’entrée (cour, couloir, allée) — comment éviter les surprises",
    description:
      "Portage long = temps de manutention. Comment l’estimer (en pas + détails), standardiser les infos, et comparer des devis sans hypothèses.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 10,
    authorSlug: "guillaume",
  },
  {
    slug: "monte-meuble-quand-indispensable",
    title: "Monte-meuble : quand c'est vraiment nécessaire (et quand ça ne l'est pas)",
    description: "Monte-meuble ou portage à la main ? Comment ça se décide, ce que ça coûte, ce qu'il faut préciser dans le devis — et pourquoi la moitié des erreurs viennent d'une fenêtre mal mesurée.",
    publishedAt: "2026-03-08T00:00:00.000Z",
    updatedAt: "2026-03-08T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 10,
    tags: ["monte-meuble", "lift déménagement", "accès difficile", "surcôût déménagement"],
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-parking-souterrain",
    title: "Déménagement avec parking souterrain : hauteur, accès camion, portage — le guide pour un devis fiable",
    description:
      "Parking souterrain = contraintes d’accès. Quelles infos donner (détails + distance), comment éviter les surprises, et checklist jour J.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 9,
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-rue-etroite-impasse",
    title: "Déménagement rue étroite / impasse : comment gérer camion, portage et éviter les galères",
    description:
      "Accès compliqué : comment cadrer la logistique (camion/portage), obtenir un devis fiable, et éviter l’improvisation le jour J.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 9,
    authorSlug: "guillaume",
  },
  {
    slug: "petit-demenagement-10-15-cartons",
    title: "Petit déménagement (10–15 cartons) : prix réaliste, options, et comment éviter de payer trop",
    description:
      "Petit volume ne veut pas dire petit risque : options, dossier devis propre, checklists et astuces budget.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 11,
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-colocation-etudiant",
    title: "Déménagement colocation / étudiant : organiser plusieurs volumes sans chaos (checklist + méthode)",
    description:
      "Méthode simple pour déménager en colocation : inventaire par personne, étiquetage, timing et checklists pour un jour J fluide.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 10,
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-objets-lourds-frigo-piano-coffre",
    title: "Objets lourds (frigo américain, piano, coffre) : les infos à donner pour éviter casse + suppléments",
    description:
      "Guide pratique : détails/informations à fournir, méthode, et comment cadrer objets lourds dans un devis sans surprises.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 12,
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-fin-de-mois-vs-milieu",
    title: "Fin de mois vs milieu de mois : quand déménager pour payer moins (sans prendre de risque)",
    description:
      "Pourquoi la fin de mois est plus tendue, comment obtenir un meilleur prix avec de la flexibilité, et checklists pour sécuriser votre déménagement.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    authorSlug: "guillaume",
  },
  {
    slug: "garde-meuble-2-semaines-avant-demenagement",
    title: "Garde-meuble avant déménagement : quand c'est utile, comment l'organiser, combien ça coûte",
    description: "Décalage entre sortie et entrée ? Garde-meuble 2 semaines : ce que ça coûte vraiment, comment choisir, ce qu'on met dedans (et ce qu'on évite), et comment l'intégrer dans le devis déménagement.",
    publishedAt: "2026-03-08T00:00:00.000Z",
    updatedAt: "2026-03-08T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 10,
    tags: ["garde-meuble", "stockage déménagement", "box stockage", "décalage bail"],
    authorSlug: "guillaume",
  },
  {
    slug: "autorisation-stationnement-demenagement-demande-modele",
    title: "Autorisation de stationnement pour déménagement : quand la demander + modèle de demande (simple)",
    description:
      "Réserver une place, éviter l’improvisation : checklist et modèle de demande pour stationnement le jour J.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 10,
    authorSlug: "lucie",
  },
  {
    slug: "cartons-gratuits-ou-trouver",
    title: "Cartons de déménagement gratuits : où en trouver vite (sans cartons pourris) + plan en 30 minutes",
    description:
      "Cartons gratuits oui, mais solides : où chercher, quels cartons éviter, et plan rapide pour s’organiser.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 9,
    authorSlug: "lucie",
  },
  {
    slug: "assurance-demenagement-dommages-que-couvre",
    title: "Assurance déménagement : que couvre vraiment la “casse” (et comment éviter les zones grises)",
    description:
      "Méthode simple : objets sensibles, détails, déclaration cohérente, et vérifs post‑déménagement pour éviter les disputes.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 10,
    authorSlug: "lucie",
  },
  {
    slug: "emballer-vaisselle-rapide-sans-casse",
    title: "Emballer la vaisselle vite (et sans casse) : méthode simple + checklist",
    description:
      "Caler, intercaler, éviter le carton trop lourd : une méthode rapide pour emballer la vaisselle sans casse.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "emballer-ecran-tv-ordinateur",
    title: "Emballer un écran TV / ordinateur sans le casser : méthode (sans carton d’origine)",
    description:
      "Rigidifier, protéger les angles, transporter sans pression : la méthode qui évite la casse des écrans.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "demenager-avec-enfants-bas-age-checklist",
    title: "Déménager avec des enfants en bas âge : plan simple (anti‑stress) + checklists",
    description:
      "Routines, zones, kit 48h : un plan concret pour un déménagement avec enfants sans chaos.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 10,
    authorSlug: "lucie",
  },
  {
    slug: "demenager-avec-chat-chien-stress",
    title: "Déménager avec un chat ou un chien : réduire le stress (avant, pendant, après) + checklist",
    description:
      "Zone safe + référent + arrivée organisée : checklists anti‑fuite et anti‑stress pour animaux.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 9,
    authorSlug: "lucie",
  },
  {
    slug: "demenager-plantes-sans-les-tuer",
    title: "Déménager des plantes sans les abîmer : méthode, protections, et erreurs à éviter",
    description:
      "Stabiliser les pots, limiter l’exposition, installer tôt : une méthode simple pour sauver vos plantes.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "demenager-frigo-americain",
    title: "Déménager un frigo américain : préparation, transport, et 7 erreurs qui le ruinent",
    description:
      "Objet lourd : accès, protection, manutention. Comment cadrer le frigo américain dans un devis sans surprises.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 9,
    authorSlug: "lucie",
  },
  {
    slug: "demenager-machine-a-laver-lave-vaisselle",
    title: "Déménager une machine à laver / lave‑vaisselle : préparation, transport (sans dégâts)",
    description:
      "Éviter les fuites et les chocs : préparation simple, calage, et organisation pour un transport propre.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "inventaire-demenagement-modele-simple",
    title: "Inventaire de déménagement : modèle simple (devis comparables) + méthode en 20 minutes",
    description:
      "3 listes + 4 détails : le format minimal qui rend les devis comparables (sans y passer la journée).",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "demenagement-sous-la-pluie-proteger",
    title: "Déménagement sous la pluie : protéger cartons, meubles, et éviter les glissades (plan simple)",
    description:
      "Zones tampon, protection minimale utile, et organisation anti‑improvisation quand il pleut.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "demenagement-canicule-ete",
    title: "Déménagement en canicule : organiser sans s’épuiser (et protéger les objets sensibles)",
    description:
      "Organisation, pauses/eau, et réduction des allers‑retours : le plan simple pour un déménagement en forte chaleur.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "demonter-remonter-canape-porte-etroite",
    title: "Canapé et porte étroite : démonter, tourner, ou lift ? (méthode pour décider vite)",
    description:
      "Passage étroit + rotation palier : méthode pour décider vite (démontage, manœuvre, lift) sans improviser.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 9,
    authorSlug: "lucie",
  },
  {
    slug: "emballer-livres-sans-carton-trop-lourd",
    title: "Emballer des livres sans faire des cartons trop lourds : méthode ultra simple (et rapide)",
    description:
      "Petits cartons, fond renforcé, étiquette “lourd” : la méthode qui évite les cartons ingérables.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 7,
    authorSlug: "lucie",
  },
  {
    slug: "etat-des-lieux-jour-demenagement-checklist",
    title: "État des lieux le jour du déménagement : checklist pour ne rien oublier (et rester zen)",
    description:
      "Placards, cave, balcon, mini tour détail : checklist “dernier passage” pour éviter les galères après.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "checklists-et-guides",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "demenager-objets-fragiles-vitrine-miroir-table",
    title: "Déménager une vitrine, un miroir, une table fragile : protections, transport, erreurs à éviter",
    description:
      "Angles protégés, rigidité, calage : les règles simples pour transporter des fragiles sans casse.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    authorSlug: "lucie",
  },
  {
    slug: "hauteur-camion-demenagement-gabarit",
    title: "Hauteur / gabarit du camion : comment éviter l’accès impossible (et le portage long)",
    description:
      "Identifier les points critiques (portail, rampe, parking) et prévoir un plan B pour stabiliser le devis.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 7,
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-weekend-comment-eviter-surcout",
    title: "Déménagement le week‑end : comment éviter le surcoût (sans tout chambouler)",
    description:
      "Flexibilité intelligente + accès clair : les leviers simples pour limiter le surcoût week‑end.",
    publishedAt: "2026-01-09T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 7,
    authorSlug: "guillaume",
  },
  {
    slug: "estimer-volume-demenagement-guide-complet",
    title: "Estimer le volume de son déménagement : guide complet 2026",
    description: "Comment calculer précisément le volume de votre déménagement en m³ pour obtenir des devis fiables. Tableaux par pièce, erreurs à éviter, méthodes pratiques.",
    publishedAt: "2026-03-06T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 9,
    tags: ["volume déménagement", "estimation", "devis"],
    authorSlug: "guillaume",
  },
  {
    slug: "comprendre-score-creditsafe-demenageur",
    title: "Score Creditsafe d'un déménageur : comment le lire et pourquoi ça compte",
    description: "Comprendre le score Creditsafe d'une entreprise de déménagement : ce qu'il mesure, comment l'interpréter, et pourquoi 257 faillites en 2024 rendent cette vérification indispensable.",
    publishedAt: "2026-03-06T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    tags: ["Creditsafe", "déménageur fiable", "vérification"],
    authorSlug: "lucie",
  },
  {
    slug: "meilleur-comparateur-demenagement-2026",
    title: "Meilleur comparateur de déménagement 2026 : comparatif honnête",
    description: "Quel est le meilleur comparateur de déménagement en 2026 ? Comparatif des plateformes : vérifications, anonymat, qualité des devis. Ce que la plupart ne vous disent pas.",
    publishedAt: "2026-03-06T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 8,
    tags: ["comparateur déménagement", "devis déménagement", "choisir"],
    authorSlug: "guillaume",
  },
  {
    slug: "comparer-devis-demenagement-guide",
    title: "Comment comparer des devis de déménagement : guide pratique 2026",
    description: "Les 7 points à vérifier pour comparer efficacement des devis de déménagement. Ce que doit contenir un devis conforme, les pièges à éviter, et comment obtenir des offres vraiment comparables.",
    publishedAt: "2026-03-06T00:00:00.000Z",
    category: "conseils-demenagement",
    readingTimeMinutes: 7,
    tags: ["devis déménagement", "comparer devis", "prix déménagement"],
    authorSlug: "guillaume",
  },
  {
    slug: "checklist-demenagement-complet",
    title: "Checklist déménagement 2026 : 70 points pour ne rien oublier",
    description: "La checklist déménagement complète : 8 semaines avant, J-30, J-7, jour J, après. 70 points vérifiés pour déménager sans stress, sans oubli, sans surprise.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    category: "Organisation",
    readingTimeMinutes: 8,
    tags: ["checklist déménagement", "organisation déménagement", "préparer déménagement"],
    authorSlug: "lucie",
  },
  {
    slug: "prix-demenagement-paris-guide",
    title: "Prix déménagement Paris 2026 : fourchettes réalistes, exemples & conseils",
    description: "Prix d'un déménagement à Paris en 2026 : fourchettes par surface (studio, T2, T3, T4), exemples chiffrés, facteurs qui font varier le prix, et comment obtenir des devis comparables.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    category: "Prix & Devis",
    readingTimeMinutes: 7,
    tags: ["prix déménagement Paris", "déménagement Paris", "tarif déménagement Paris"],
    authorSlug: "guillaume",
  },
  {
    slug: "devis-demenagement-gratuit-sans-engagement",
    title: "Devis déménagement gratuit sans engagement : comment ça marche vraiment ?",
    description: "Comment obtenir des devis de déménagement gratuits et sans engagement en 2026 ? Ce que couvre un devis, les pièges à éviter, et comment comparer des devis réellement comparables.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    category: "Prix & Devis",
    readingTimeMinutes: 7,
    tags: ["devis déménagement gratuit", "devis sans engagement", "comparer devis déménagement"],
    authorSlug: "guillaume",
  },
  {
    slug: "demenagement-juillet-aout-prix",
    title: "Déménagement en juillet-août 2026 : prix, disponibilités et comment s'organiser",
    description: "Déménager en juillet ou août coûte 30 à 50 % plus cher. Pourquoi, combien, et comment s'organiser (ou décaler) pour la haute saison du déménagement en France.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    category: "Prix & Devis",
    readingTimeMinutes: 7,
    tags: ["déménagement été", "déménagement juillet août", "prix déménagement haute saison"],
    authorSlug: "guillaume",
  },
  {
    slug: "verifier-demenageur-creditsafe-siren",
    title: "Comment vérifier un déménageur avant de signer : SIREN, Creditsafe, assurance (guide 2026)",
    description: "Guide complet pour vérifier la fiabilité d'un déménageur avant de signer : SIREN, score Creditsafe, assurance RC Pro, avis Google, procédures judiciaires. Checklist et outils gratuits.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    category: "Vérification & Fiabilité",
    readingTimeMinutes: 8,
    tags: ["vérifier déménageur", "Creditsafe déménageur", "fiabilité déménageur", "SIREN déménageur"],
    authorSlug: "lucie",
  },
  {
    slug: "supplement-prix-jour-j-comment-eviter",
    title: "Supplément de prix le jour du déménagement : causes, montants, et comment l'éviter",
    description: "40-50 % des déménagements subissent un supplément le jour J. Causes, montants typiques, et méthode concrète pour éviter les mauvaises surprises sur le prix de votre déménagement.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    category: "Prix & Devis",
    readingTimeMinutes: 7,
    tags: ["supplément déménagement", "prix déménagement jour J", "surprise prix déménagement"],
    authorSlug: "guillaume",
  },
  {
    slug: "assurance-demenagement-que-couvre",
    title: "Assurance déménagement : ce qui est couvert, ce qui ne l'est pas, et comment se protéger",
    description: "Assurance déménagement en 2026 : RC Pro du déménageur, assurance marchandises, déclaration de valeur, franchise. Ce que couvre vraiment l'assurance et comment éviter les mauvaises surprises en cas de casse.",
    publishedAt: "2026-03-07T00:00:00.000Z",
    category: "Vérification & Fiabilité",
    readingTimeMinutes: 8,
    tags: ["assurance déménagement", "RC Pro déménageur", "casse déménagement", "déclaration de valeur"],
    authorSlug: "lucie",
  },
];


