// Liste "source" des villes à ajouter (nameCapitalized + région).
// Les slugs sont générés automatiquement via slugifyCityName().
export const EXTRA_CITIES: Array<{ nameCapitalized: string; region: string }> = [
  // Île-de-France
  { nameCapitalized: "Boulogne-Billancourt", region: "Île-de-France" },
  { nameCapitalized: "Saint-Denis", region: "Île-de-France" },
  { nameCapitalized: "Argenteuil", region: "Île-de-France" },
  { nameCapitalized: "Montreuil", region: "Île-de-France" },
  { nameCapitalized: "Nanterre", region: "Île-de-France" },
  { nameCapitalized: "Versailles", region: "Île-de-France" },
  { nameCapitalized: "Courbevoie", region: "Île-de-France" },
  { nameCapitalized: "Colombes", region: "Île-de-France" },
  { nameCapitalized: "Asnières-sur-Seine", region: "Île-de-France" },
  { nameCapitalized: "Aulnay-sous-Bois", region: "Île-de-France" },
  { nameCapitalized: "Rueil-Malmaison", region: "Île-de-France" },
  { nameCapitalized: "Aubervilliers", region: "Île-de-France" },
  { nameCapitalized: "Champigny-sur-Marne", region: "Île-de-France" },
  { nameCapitalized: "Drancy", region: "Île-de-France" },
  { nameCapitalized: "Issy-les-Moulineaux", region: "Île-de-France" },
  { nameCapitalized: "Noisy-le-Grand", region: "Île-de-France" },
  { nameCapitalized: "Levallois-Perret", region: "Île-de-France" },
  { nameCapitalized: "Clichy", region: "Île-de-France" },
  { nameCapitalized: "Créteil", region: "Île-de-France" },
  { nameCapitalized: "Vitry-sur-Seine", region: "Île-de-France" },
  { nameCapitalized: "Ivry-sur-Seine", region: "Île-de-France" },
  { nameCapitalized: "Neuilly-sur-Seine", region: "Île-de-France" },
  { nameCapitalized: "Villejuif", region: "Île-de-France" },
  { nameCapitalized: "Sarcelles", region: "Île-de-France" },
  { nameCapitalized: "Bobigny", region: "Île-de-France" },
  { nameCapitalized: "Bondy", region: "Île-de-France" },
  { nameCapitalized: "Pantin", region: "Île-de-France" },
  { nameCapitalized: "Fontenay-sous-Bois", region: "Île-de-France" },
  { nameCapitalized: "Maisons-Alfort", region: "Île-de-France" },
  { nameCapitalized: "Le Blanc-Mesnil", region: "Île-de-France" },
  { nameCapitalized: "Épinay-sur-Seine", region: "Île-de-France" },
  { nameCapitalized: "Vincennes", region: "Île-de-France" },
  { nameCapitalized: "Montrouge", region: "Île-de-France" },
  { nameCapitalized: "Saint-Ouen-sur-Seine", region: "Île-de-France" },
  { nameCapitalized: "Saint-Maur-des-Fossés", region: "Île-de-France" },
  { nameCapitalized: "Alfortville", region: "Île-de-France" },
  { nameCapitalized: "Massy", region: "Île-de-France" },
  { nameCapitalized: "Antony", region: "Île-de-France" },
  { nameCapitalized: "Corbeil-Essonnes", region: "Île-de-France" },
  { nameCapitalized: "Évry-Courcouronnes", region: "Île-de-France" },
  { nameCapitalized: "Poissy", region: "Île-de-France" },
  { nameCapitalized: "Sartrouville", region: "Île-de-France" },
  { nameCapitalized: "Saint-Germain-en-Laye", region: "Île-de-France" },
  { nameCapitalized: "Mantes-la-Jolie", region: "Île-de-France" },
  { nameCapitalized: "Cergy", region: "Île-de-France" },
  { nameCapitalized: "Pontoise", region: "Île-de-France" },

  // Auvergne-Rhône-Alpes (hors déjà présents)
  { nameCapitalized: "Villeurbanne", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Saint-Étienne", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Clermont-Ferrand", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Annecy", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Chambéry", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Valence", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Bourg-en-Bresse", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Roanne", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Vénissieux", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Saint-Priest", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Caluire-et-Cuire", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Échirolles", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Saint-Martin-d'Hères", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Vaulx-en-Velin", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Bron", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Décines-Charpieu", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Villefranche-sur-Saône", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Vichy", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Montluçon", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Moulins", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Issoire", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Le Puy-en-Velay", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Aurillac", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Le Chambon-Feugerolles", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Saint-Chamond", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Firminy", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Annonay", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Romans-sur-Isère", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Bourg-lès-Valence", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Oyonnax", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Annemasse", region: "Auvergne-Rhône-Alpes" },
  { nameCapitalized: "Thonon-les-Bains", region: "Auvergne-Rhône-Alpes" },

  // Provence-Alpes-Côte d'Azur (hors déjà présents)
  { nameCapitalized: "Aix-en-Provence", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Avignon", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Cannes", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Antibes", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "La Seyne-sur-Mer", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Hyères", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Fréjus", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Saint-Raphaël", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Arles", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Martigues", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Salon-de-Provence", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Istres", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "La Ciotat", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Grasse", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Cagnes-sur-Mer", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Saint-Laurent-du-Var", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Menton", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Draguignan", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Brignoles", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Gap", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Digne-les-Bains", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Manosque", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Orange", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Carpentras", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Cavaillon", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Sorgues", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Le Pontet", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Vitrolles", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Marignane", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Les Pennes-Mirabeau", region: "Provence-Alpes-Côte d'Azur" },
  { nameCapitalized: "Gardanne", region: "Provence-Alpes-Côte d'Azur" },

  // Occitanie (hors déjà présents)
  { nameCapitalized: "Nîmes", region: "Occitanie" },
  { nameCapitalized: "Perpignan", region: "Occitanie" },
  { nameCapitalized: "Béziers", region: "Occitanie" },
  { nameCapitalized: "Narbonne", region: "Occitanie" },
  { nameCapitalized: "Montauban", region: "Occitanie" },
  { nameCapitalized: "Albi", region: "Occitanie" },
  { nameCapitalized: "Carcassonne", region: "Occitanie" },
  { nameCapitalized: "Sète", region: "Occitanie" },
  { nameCapitalized: "Tarbes", region: "Occitanie" },
  { nameCapitalized: "Alès", region: "Occitanie" },
  { nameCapitalized: "Colomiers", region: "Occitanie" },
  { nameCapitalized: "Tournefeuille", region: "Occitanie" },
  { nameCapitalized: "Blagnac", region: "Occitanie" },
  { nameCapitalized: "Muret", region: "Occitanie" },
  { nameCapitalized: "Castres", region: "Occitanie" },
  { nameCapitalized: "Mazamet", region: "Occitanie" },
  { nameCapitalized: "Rodez", region: "Occitanie" },
  { nameCapitalized: "Millau", region: "Occitanie" },
  { nameCapitalized: "Cahors", region: "Occitanie" },
  { nameCapitalized: "Figeac", region: "Occitanie" },
  { nameCapitalized: "Auch", region: "Occitanie" },
  { nameCapitalized: "Frontignan", region: "Occitanie" },
  { nameCapitalized: "Lunel", region: "Occitanie" },
  { nameCapitalized: "Agde", region: "Occitanie" },

  // Nouvelle-Aquitaine (hors déjà présents)
  { nameCapitalized: "Mérignac", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Pessac", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Talence", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Bègles", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Villenave-d'Ornon", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Cenon", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Floirac", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Libourne", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Arcachon", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "La Rochelle", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Niort", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Poitiers", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Limoges", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Angoulême", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Brive-la-Gaillarde", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Périgueux", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Bergerac", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Agen", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Bayonne", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Pau", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Biarritz", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Anglet", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Saintes", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Royan", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Rochefort", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Châtellerault", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Guéret", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Tulle", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Ussel", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Dax", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Hendaye", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Lormont", region: "Nouvelle-Aquitaine" },
  { nameCapitalized: "Gradignan", region: "Nouvelle-Aquitaine" },

  // Hauts-de-France (hors déjà présents)
  { nameCapitalized: "Roubaix", region: "Hauts-de-France" },
  { nameCapitalized: "Tourcoing", region: "Hauts-de-France" },
  { nameCapitalized: "Amiens", region: "Hauts-de-France" },
  { nameCapitalized: "Dunkerque", region: "Hauts-de-France" },
  { nameCapitalized: "Calais", region: "Hauts-de-France" },
  { nameCapitalized: "Boulogne-sur-Mer", region: "Hauts-de-France" },
  { nameCapitalized: "Saint-Quentin", region: "Hauts-de-France" },
  { nameCapitalized: "Beauvais", region: "Hauts-de-France" },
  { nameCapitalized: "Compiègne", region: "Hauts-de-France" },
  { nameCapitalized: "Creil", region: "Hauts-de-France" },
  { nameCapitalized: "Arras", region: "Hauts-de-France" },
  { nameCapitalized: "Lens", region: "Hauts-de-France" },
  { nameCapitalized: "Liévin", region: "Hauts-de-France" },
  { nameCapitalized: "Béthune", region: "Hauts-de-France" },
  { nameCapitalized: "Hazebrouck", region: "Hauts-de-France" },
  { nameCapitalized: "Valenciennes", region: "Hauts-de-France" },
  { nameCapitalized: "Denain", region: "Hauts-de-France" },
  { nameCapitalized: "Cambrai", region: "Hauts-de-France" },
  { nameCapitalized: "Douai", region: "Hauts-de-France" },
  { nameCapitalized: "Wattrelos", region: "Hauts-de-France" },
  { nameCapitalized: "Villeneuve-d'Ascq", region: "Hauts-de-France" },
  { nameCapitalized: "Maubeuge", region: "Hauts-de-France" },

  // Grand Est (hors déjà présents)
  { nameCapitalized: "Metz", region: "Grand Est" },
  { nameCapitalized: "Nancy", region: "Grand Est" },
  { nameCapitalized: "Mulhouse", region: "Grand Est" },
  { nameCapitalized: "Colmar", region: "Grand Est" },
  { nameCapitalized: "Thionville", region: "Grand Est" },
  { nameCapitalized: "Troyes", region: "Grand Est" },
  { nameCapitalized: "Charleville-Mézières", region: "Grand Est" },
  { nameCapitalized: "Châlons-en-Champagne", region: "Grand Est" },
  { nameCapitalized: "Épernay", region: "Grand Est" },
  { nameCapitalized: "Haguenau", region: "Grand Est" },
  { nameCapitalized: "Schiltigheim", region: "Grand Est" },
  { nameCapitalized: "Illkirch-Graffenstaden", region: "Grand Est" },
  { nameCapitalized: "Sélestat", region: "Grand Est" },
  { nameCapitalized: "Saverne", region: "Grand Est" },
  { nameCapitalized: "Saint-Dié-des-Vosges", region: "Grand Est" },
  { nameCapitalized: "Épinal", region: "Grand Est" },
  { nameCapitalized: "Lunéville", region: "Grand Est" },
  { nameCapitalized: "Bar-le-Duc", region: "Grand Est" },
  { nameCapitalized: "Verdun", region: "Grand Est" },
  { nameCapitalized: "Vitry-le-François", region: "Grand Est" },
  { nameCapitalized: "Saint-Avold", region: "Grand Est" },
  { nameCapitalized: "Forbach", region: "Grand Est" },
  { nameCapitalized: "Sarreguemines", region: "Grand Est" },

  // Pays de la Loire (hors déjà présents)
  { nameCapitalized: "Le Mans", region: "Pays de la Loire" },
  { nameCapitalized: "Saint-Nazaire", region: "Pays de la Loire" },
  { nameCapitalized: "Cholet", region: "Pays de la Loire" },
  { nameCapitalized: "Laval", region: "Pays de la Loire" },
  { nameCapitalized: "La Roche-sur-Yon", region: "Pays de la Loire" },
  { nameCapitalized: "Rezé", region: "Pays de la Loire" },
  { nameCapitalized: "Saint-Herblain", region: "Pays de la Loire" },
  { nameCapitalized: "Saint-Sébastien-sur-Loire", region: "Pays de la Loire" },
  { nameCapitalized: "Orvault", region: "Pays de la Loire" },
  { nameCapitalized: "Vertou", region: "Pays de la Loire" },
  { nameCapitalized: "Carquefou", region: "Pays de la Loire" },
  { nameCapitalized: "Bouguenais", region: "Pays de la Loire" },
  { nameCapitalized: "Les Sables-d'Olonne", region: "Pays de la Loire" },
  { nameCapitalized: "Saumur", region: "Pays de la Loire" },
  { nameCapitalized: "Sablé-sur-Sarthe", region: "Pays de la Loire" },
  { nameCapitalized: "Mayenne", region: "Pays de la Loire" },
  { nameCapitalized: "Challans", region: "Pays de la Loire" },
  { nameCapitalized: "Pornic", region: "Pays de la Loire" },

  // Bretagne (hors déjà présents)
  { nameCapitalized: "Brest", region: "Bretagne" },
  { nameCapitalized: "Quimper", region: "Bretagne" },
  { nameCapitalized: "Lorient", region: "Bretagne" },
  { nameCapitalized: "Vannes", region: "Bretagne" },
  { nameCapitalized: "Saint-Brieuc", region: "Bretagne" },
  { nameCapitalized: "Saint-Malo", region: "Bretagne" },
  { nameCapitalized: "Lannion", region: "Bretagne" },
  { nameCapitalized: "Morlaix", region: "Bretagne" },
  { nameCapitalized: "Concarneau", region: "Bretagne" },
  { nameCapitalized: "Pontivy", region: "Bretagne" },
  { nameCapitalized: "Auray", region: "Bretagne" },
  { nameCapitalized: "Dinan", region: "Bretagne" },
  { nameCapitalized: "Fougères", region: "Bretagne" },
  { nameCapitalized: "Vitré", region: "Bretagne" },
  { nameCapitalized: "Ploemeur", region: "Bretagne" },
  { nameCapitalized: "Cesson-Sévigné", region: "Bretagne" },

  // Normandie (hors déjà présents)
  { nameCapitalized: "Caen", region: "Normandie" },
  { nameCapitalized: "Cherbourg-en-Cotentin", region: "Normandie" },
  { nameCapitalized: "Évreux", region: "Normandie" },
  { nameCapitalized: "Dieppe", region: "Normandie" },
  { nameCapitalized: "Sotteville-lès-Rouen", region: "Normandie" },
  { nameCapitalized: "Saint-Étienne-du-Rouvray", region: "Normandie" },
  { nameCapitalized: "Elbeuf", region: "Normandie" },
  { nameCapitalized: "Lisieux", region: "Normandie" },
  { nameCapitalized: "Alençon", region: "Normandie" },
  { nameCapitalized: "Granville", region: "Normandie" },

  // Centre-Val de Loire (hors déjà présents)
  { nameCapitalized: "Orléans", region: "Centre-Val de Loire" },
  { nameCapitalized: "Blois", region: "Centre-Val de Loire" },
  { nameCapitalized: "Bourges", region: "Centre-Val de Loire" },
  { nameCapitalized: "Chartres", region: "Centre-Val de Loire" },
  { nameCapitalized: "Châteauroux", region: "Centre-Val de Loire" },
  { nameCapitalized: "Vierzon", region: "Centre-Val de Loire" },
  { nameCapitalized: "Joué-lès-Tours", region: "Centre-Val de Loire" },
  { nameCapitalized: "Saint-Cyr-sur-Loire", region: "Centre-Val de Loire" },
  { nameCapitalized: "Saint-Jean-de-Braye", region: "Centre-Val de Loire" },
  { nameCapitalized: "Olivet", region: "Centre-Val de Loire" },
  { nameCapitalized: "Vendôme", region: "Centre-Val de Loire" },
  { nameCapitalized: "Montargis", region: "Centre-Val de Loire" },

  // Bourgogne–Franche-Comté (hors déjà présents)
  { nameCapitalized: "Besançon", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Belfort", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Chalon-sur-Saône", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Mâcon", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Auxerre", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Nevers", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Sens", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Montbéliard", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Lons-le-Saunier", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Dole", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Beaune", region: "Bourgogne-Franche-Comté" },
  { nameCapitalized: "Le Creusot", region: "Bourgogne-Franche-Comté" },

  // Corse
  { nameCapitalized: "Ajaccio", region: "Corse" },
  { nameCapitalized: "Bastia", region: "Corse" },
];


