/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: 'standalone',
  trailingSlash: true,

  async redirects() {
    return [
      // ============================================
      // MARSEILLE (devis-demenageur-marseille.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/marseille/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }],
      },
      { source: '/quartiers-marseille', destination: 'https://moverz.fr/quartiers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/quartiers-marseille/', destination: 'https://moverz.fr/quartiers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/vieux-port', destination: 'https://moverz.fr/marseille/vieux-port/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/vieux-port/', destination: 'https://moverz.fr/marseille/vieux-port/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/panier', destination: 'https://moverz.fr/marseille/panier/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/panier/', destination: 'https://moverz.fr/marseille/panier/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/joliette', destination: 'https://moverz.fr/marseille/joliette/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/joliette/', destination: 'https://moverz.fr/marseille/joliette/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/endoume', destination: 'https://moverz.fr/marseille/endoume/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/endoume/', destination: 'https://moverz.fr/marseille/endoume/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/plaine', destination: 'https://moverz.fr/marseille/plaine/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/plaine/', destination: 'https://moverz.fr/marseille/plaine/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-paris', destination: 'https://moverz.fr/marseille-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-paris/', destination: 'https://moverz.fr/marseille-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-lyon', destination: 'https://moverz.fr/marseille-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-lyon/', destination: 'https://moverz.fr/marseille-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-toulouse', destination: 'https://moverz.fr/marseille-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-toulouse/', destination: 'https://moverz.fr/marseille-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-nantes', destination: 'https://moverz.fr/marseille-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-nantes/', destination: 'https://moverz.fr/marseille-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-espagne', destination: 'https://moverz.fr/marseille-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      { source: '/marseille-vers-espagne/', destination: 'https://moverz.fr/marseille-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-marseille.fr' }],
      },

      // ============================================
      // LYON (devis-demenageur-lyon.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/lyon/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }],
      },
      { source: '/quartiers-lyon', destination: 'https://moverz.fr/quartiers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/quartiers-lyon/', destination: 'https://moverz.fr/quartiers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/presquile', destination: 'https://moverz.fr/lyon/presquile/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/presquile/', destination: 'https://moverz.fr/lyon/presquile/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/vieux-lyon', destination: 'https://moverz.fr/lyon/vieux-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/vieux-lyon/', destination: 'https://moverz.fr/lyon/vieux-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/part-dieu', destination: 'https://moverz.fr/lyon/part-dieu/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/part-dieu/', destination: 'https://moverz.fr/lyon/part-dieu/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/croix-rousse', destination: 'https://moverz.fr/lyon/croix-rousse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/croix-rousse/', destination: 'https://moverz.fr/lyon/croix-rousse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/confluence', destination: 'https://moverz.fr/lyon/confluence/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/confluence/', destination: 'https://moverz.fr/lyon/confluence/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-paris', destination: 'https://moverz.fr/lyon-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-paris/', destination: 'https://moverz.fr/lyon-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-marseille', destination: 'https://moverz.fr/lyon-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-marseille/', destination: 'https://moverz.fr/lyon-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-toulouse', destination: 'https://moverz.fr/lyon-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-toulouse/', destination: 'https://moverz.fr/lyon-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-geneve', destination: 'https://moverz.fr/lyon-vers-geneve/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-geneve/', destination: 'https://moverz.fr/lyon-vers-geneve/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-grenoble', destination: 'https://moverz.fr/lyon-vers-grenoble/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      { source: '/lyon-vers-grenoble/', destination: 'https://moverz.fr/lyon-vers-grenoble/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-lyon.fr' }],
      },

      // ============================================
      // BORDEAUX (www.bordeaux-demenageur.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/bordeaux/',
        permanent: true,
        has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }],
      },
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/bordeaux/',
        permanent: true,
        has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }],
      },
      { source: '/quartiers-bordeaux', destination: 'https://moverz.fr/quartiers-bordeaux/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/quartiers-bordeaux/', destination: 'https://moverz.fr/quartiers-bordeaux/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/quartiers-bordeaux', destination: 'https://moverz.fr/quartiers-bordeaux/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/quartiers-bordeaux/', destination: 'https://moverz.fr/quartiers-bordeaux/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/chartrons', destination: 'https://moverz.fr/bordeaux/chartrons/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/chartrons/', destination: 'https://moverz.fr/bordeaux/chartrons/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/chartrons', destination: 'https://moverz.fr/bordeaux/chartrons/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/chartrons/', destination: 'https://moverz.fr/bordeaux/chartrons/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/saint-pierre', destination: 'https://moverz.fr/bordeaux/saint-pierre/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/saint-pierre/', destination: 'https://moverz.fr/bordeaux/saint-pierre/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/saint-pierre', destination: 'https://moverz.fr/bordeaux/saint-pierre/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/saint-pierre/', destination: 'https://moverz.fr/bordeaux/saint-pierre/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/victoire', destination: 'https://moverz.fr/bordeaux/victoire/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/victoire/', destination: 'https://moverz.fr/bordeaux/victoire/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/victoire', destination: 'https://moverz.fr/bordeaux/victoire/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/victoire/', destination: 'https://moverz.fr/bordeaux/victoire/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bastide', destination: 'https://moverz.fr/bordeaux/bastide/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bastide/', destination: 'https://moverz.fr/bordeaux/bastide/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bastide', destination: 'https://moverz.fr/bordeaux/bastide/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bastide/', destination: 'https://moverz.fr/bordeaux/bastide/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/lac', destination: 'https://moverz.fr/bordeaux/lac/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/lac/', destination: 'https://moverz.fr/bordeaux/lac/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/lac', destination: 'https://moverz.fr/bordeaux/lac/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/lac/', destination: 'https://moverz.fr/bordeaux/lac/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-paris', destination: 'https://moverz.fr/bordeaux-vers-paris/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-paris/', destination: 'https://moverz.fr/bordeaux-vers-paris/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-paris', destination: 'https://moverz.fr/bordeaux-vers-paris/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-paris/', destination: 'https://moverz.fr/bordeaux-vers-paris/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-toulouse', destination: 'https://moverz.fr/bordeaux-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-toulouse/', destination: 'https://moverz.fr/bordeaux-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-toulouse', destination: 'https://moverz.fr/bordeaux-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-toulouse/', destination: 'https://moverz.fr/bordeaux-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-lyon', destination: 'https://moverz.fr/bordeaux-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-lyon/', destination: 'https://moverz.fr/bordeaux-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-lyon', destination: 'https://moverz.fr/bordeaux-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-lyon/', destination: 'https://moverz.fr/bordeaux-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-nantes', destination: 'https://moverz.fr/bordeaux-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-nantes/', destination: 'https://moverz.fr/bordeaux-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-nantes', destination: 'https://moverz.fr/bordeaux-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-nantes/', destination: 'https://moverz.fr/bordeaux-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-espagne', destination: 'https://moverz.fr/bordeaux-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-espagne/', destination: 'https://moverz.fr/bordeaux-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-espagne', destination: 'https://moverz.fr/bordeaux-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      { source: '/bordeaux-vers-espagne/', destination: 'https://moverz.fr/bordeaux-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'bordeaux-demenageur.fr' }],
      },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'www.bordeaux-demenageur.fr' }],
      },

      // ============================================
      // LILLE (devis-demenageur-lille.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/lille/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }],
      },
      { source: '/quartiers-lille', destination: 'https://moverz.fr/quartiers-lille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/quartiers-lille/', destination: 'https://moverz.fr/quartiers-lille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/vieux-lille', destination: 'https://moverz.fr/lille/vieux-lille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/vieux-lille/', destination: 'https://moverz.fr/lille/vieux-lille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/wazemmes', destination: 'https://moverz.fr/lille/wazemmes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/wazemmes/', destination: 'https://moverz.fr/lille/wazemmes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/republique', destination: 'https://moverz.fr/lille/republique/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/republique/', destination: 'https://moverz.fr/lille/republique/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/vauban', destination: 'https://moverz.fr/lille/vauban/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/vauban/', destination: 'https://moverz.fr/lille/vauban/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/moulins', destination: 'https://moverz.fr/lille/moulins/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/moulins/', destination: 'https://moverz.fr/lille/moulins/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-paris', destination: 'https://moverz.fr/lille-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-paris/', destination: 'https://moverz.fr/lille-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-bruxelles', destination: 'https://moverz.fr/lille-vers-bruxelles/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-bruxelles/', destination: 'https://moverz.fr/lille-vers-bruxelles/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-lyon', destination: 'https://moverz.fr/lille-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-lyon/', destination: 'https://moverz.fr/lille-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-londres', destination: 'https://moverz.fr/lille-vers-londres/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-londres/', destination: 'https://moverz.fr/lille-vers-londres/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-gand', destination: 'https://moverz.fr/lille-vers-gand/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      { source: '/lille-vers-gand/', destination: 'https://moverz.fr/lille-vers-gand/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-lille.fr' }],
      },

      // ============================================
      // NICE (devis-demenageur-nice.fr)
      // ============================================
      // Home
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/nice/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }],
      },
      // Hub quartiers
      {
        source: '/quartiers-nice',
        destination: 'https://moverz.fr/quartiers-nice/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }],
      },
      {
        source: '/quartiers-nice/',
        destination: 'https://moverz.fr/quartiers-nice/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }],
      },
      // Quartiers
      { source: '/vieux-nice', destination: 'https://moverz.fr/nice/vieux-nice/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/vieux-nice/', destination: 'https://moverz.fr/nice/vieux-nice/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/port', destination: 'https://moverz.fr/nice/port/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/port/', destination: 'https://moverz.fr/nice/port/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/liberation', destination: 'https://moverz.fr/nice/liberation/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/liberation/', destination: 'https://moverz.fr/nice/liberation/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/cimiez', destination: 'https://moverz.fr/nice/cimiez/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/cimiez/', destination: 'https://moverz.fr/nice/cimiez/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/riquier', destination: 'https://moverz.fr/nice/riquier/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/riquier/', destination: 'https://moverz.fr/nice/riquier/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      // Corridors
      { source: '/nice-vers-paris', destination: 'https://moverz.fr/nice-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-paris/', destination: 'https://moverz.fr/nice-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-marseille', destination: 'https://moverz.fr/nice-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-marseille/', destination: 'https://moverz.fr/nice-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-lyon', destination: 'https://moverz.fr/nice-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-lyon/', destination: 'https://moverz.fr/nice-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-italie', destination: 'https://moverz.fr/nice-vers-italie/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-italie/', destination: 'https://moverz.fr/nice-vers-italie/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-monaco', destination: 'https://moverz.fr/nice-vers-monaco/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      { source: '/nice-vers-monaco/', destination: 'https://moverz.fr/nice-vers-monaco/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }] },
      // Blog
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-nice.fr' }],
      },

      // ============================================
      // TOULOUSE (devis-demenageur-toulousain.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/toulouse/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }],
      },
      { source: '/quartiers-toulouse', destination: 'https://moverz.fr/quartiers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/quartiers-toulouse/', destination: 'https://moverz.fr/quartiers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/capitole', destination: 'https://moverz.fr/toulouse/capitole/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/capitole/', destination: 'https://moverz.fr/toulouse/capitole/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/saint-cyprien', destination: 'https://moverz.fr/toulouse/saint-cyprien/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/saint-cyprien/', destination: 'https://moverz.fr/toulouse/saint-cyprien/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/carmes', destination: 'https://moverz.fr/toulouse/carmes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/carmes/', destination: 'https://moverz.fr/toulouse/carmes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/compans', destination: 'https://moverz.fr/toulouse/compans/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/compans/', destination: 'https://moverz.fr/toulouse/compans/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/jean-jaures', destination: 'https://moverz.fr/toulouse/jean-jaures/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/jean-jaures/', destination: 'https://moverz.fr/toulouse/jean-jaures/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-paris', destination: 'https://moverz.fr/toulouse-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-paris/', destination: 'https://moverz.fr/toulouse-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-lyon', destination: 'https://moverz.fr/toulouse-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-lyon/', destination: 'https://moverz.fr/toulouse-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-marseille', destination: 'https://moverz.fr/toulouse-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-marseille/', destination: 'https://moverz.fr/toulouse-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-nantes', destination: 'https://moverz.fr/toulouse-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-nantes/', destination: 'https://moverz.fr/toulouse-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-espagne', destination: 'https://moverz.fr/toulouse-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      { source: '/toulouse-vers-espagne/', destination: 'https://moverz.fr/toulouse-vers-espagne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-toulousain.fr' }],
      },

      // ============================================
      // STRASBOURG (devis-demenageur-strasbourg.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/strasbourg/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }],
      },
      { source: '/quartiers-strasbourg', destination: 'https://moverz.fr/quartiers-strasbourg/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/quartiers-strasbourg/', destination: 'https://moverz.fr/quartiers-strasbourg/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/grande-ile', destination: 'https://moverz.fr/strasbourg/grande-ile/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/grande-ile/', destination: 'https://moverz.fr/strasbourg/grande-ile/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/neudorf', destination: 'https://moverz.fr/strasbourg/neudorf/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/neudorf/', destination: 'https://moverz.fr/strasbourg/neudorf/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/cronenbourg', destination: 'https://moverz.fr/strasbourg/cronenbourg/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/cronenbourg/', destination: 'https://moverz.fr/strasbourg/cronenbourg/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/koenigshoffen', destination: 'https://moverz.fr/strasbourg/koenigshoffen/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/koenigshoffen/', destination: 'https://moverz.fr/strasbourg/koenigshoffen/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/robertsau', destination: 'https://moverz.fr/strasbourg/robertsau/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/robertsau/', destination: 'https://moverz.fr/strasbourg/robertsau/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-paris', destination: 'https://moverz.fr/strasbourg-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-paris/', destination: 'https://moverz.fr/strasbourg-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-lyon', destination: 'https://moverz.fr/strasbourg-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-lyon/', destination: 'https://moverz.fr/strasbourg-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-mulhouse', destination: 'https://moverz.fr/strasbourg-vers-mulhouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-mulhouse/', destination: 'https://moverz.fr/strasbourg-vers-mulhouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-allemagne', destination: 'https://moverz.fr/strasbourg-vers-allemagne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-allemagne/', destination: 'https://moverz.fr/strasbourg-vers-allemagne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-suisse', destination: 'https://moverz.fr/strasbourg-vers-suisse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      { source: '/strasbourg-vers-suisse/', destination: 'https://moverz.fr/strasbourg-vers-suisse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-strasbourg.fr' }],
      },

      // ============================================
      // NANTES (devis-demenageur-nantes.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/nantes/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }],
      },
      { source: '/quartiers-nantes', destination: 'https://moverz.fr/quartiers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/quartiers-nantes/', destination: 'https://moverz.fr/quartiers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/bouffay', destination: 'https://moverz.fr/nantes/bouffay/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/bouffay/', destination: 'https://moverz.fr/nantes/bouffay/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/ile-de-nantes', destination: 'https://moverz.fr/nantes/ile-de-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/ile-de-nantes/', destination: 'https://moverz.fr/nantes/ile-de-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/doulon', destination: 'https://moverz.fr/nantes/doulon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/doulon/', destination: 'https://moverz.fr/nantes/doulon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/beaujoire', destination: 'https://moverz.fr/nantes/beaujoire/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/beaujoire/', destination: 'https://moverz.fr/nantes/beaujoire/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/hauts-paves', destination: 'https://moverz.fr/nantes/hauts-paves/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/hauts-paves/', destination: 'https://moverz.fr/nantes/hauts-paves/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-paris', destination: 'https://moverz.fr/nantes-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-paris/', destination: 'https://moverz.fr/nantes-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-bordeaux', destination: 'https://moverz.fr/nantes-vers-bordeaux/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-bordeaux/', destination: 'https://moverz.fr/nantes-vers-bordeaux/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-rennes', destination: 'https://moverz.fr/nantes-vers-rennes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-rennes/', destination: 'https://moverz.fr/nantes-vers-rennes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-lyon', destination: 'https://moverz.fr/nantes-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-lyon/', destination: 'https://moverz.fr/nantes-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-la-baule', destination: 'https://moverz.fr/nantes-vers-la-baule/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      { source: '/nantes-vers-la-baule/', destination: 'https://moverz.fr/nantes-vers-la-baule/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-nantes.fr' }],
      },
      
      // ============================================
      // RENNES (devis-demenageur-rennes.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/rennes/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }],
      },
      { source: '/quartiers-rennes', destination: 'https://moverz.fr/quartiers-rennes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/quartiers-rennes/', destination: 'https://moverz.fr/quartiers-rennes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/centre', destination: 'https://moverz.fr/rennes/centre/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/centre/', destination: 'https://moverz.fr/rennes/centre/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/thabor', destination: 'https://moverz.fr/rennes/thabor/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/thabor/', destination: 'https://moverz.fr/rennes/thabor/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/maurepas', destination: 'https://moverz.fr/rennes/maurepas/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/maurepas/', destination: 'https://moverz.fr/rennes/maurepas/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/villejean', destination: 'https://moverz.fr/rennes/villejean/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/villejean/', destination: 'https://moverz.fr/rennes/villejean/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/cleunay', destination: 'https://moverz.fr/rennes/cleunay/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/cleunay/', destination: 'https://moverz.fr/rennes/cleunay/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-paris', destination: 'https://moverz.fr/rennes-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-paris/', destination: 'https://moverz.fr/rennes-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-nantes', destination: 'https://moverz.fr/rennes-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-nantes/', destination: 'https://moverz.fr/rennes-vers-nantes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-brest', destination: 'https://moverz.fr/rennes-vers-brest/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-brest/', destination: 'https://moverz.fr/rennes-vers-brest/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-saint-malo', destination: 'https://moverz.fr/rennes-vers-saint-malo/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-saint-malo/', destination: 'https://moverz.fr/rennes-vers-saint-malo/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-angers', destination: 'https://moverz.fr/rennes-vers-angers/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      { source: '/rennes-vers-angers/', destination: 'https://moverz.fr/rennes-vers-angers/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-rennes.fr' }],
      },
      
      // ============================================
      // ROUEN (devis-demenageur-rouen.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/rouen/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }],
      },
      { source: '/quartiers-rouen', destination: 'https://moverz.fr/quartiers-rouen/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/quartiers-rouen/', destination: 'https://moverz.fr/quartiers-rouen/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/centre-historique', destination: 'https://moverz.fr/rouen/centre-historique/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/centre-historique/', destination: 'https://moverz.fr/rouen/centre-historique/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/saint-sever', destination: 'https://moverz.fr/rouen/saint-sever/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/saint-sever/', destination: 'https://moverz.fr/rouen/saint-sever/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/grammont', destination: 'https://moverz.fr/rouen/grammont/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/grammont/', destination: 'https://moverz.fr/rouen/grammont/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/sapins', destination: 'https://moverz.fr/rouen/sapins/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/sapins/', destination: 'https://moverz.fr/rouen/sapins/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/madrillet', destination: 'https://moverz.fr/rouen/madrillet/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/madrillet/', destination: 'https://moverz.fr/rouen/madrillet/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-paris', destination: 'https://moverz.fr/rouen-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-paris/', destination: 'https://moverz.fr/rouen-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-le-havre', destination: 'https://moverz.fr/rouen-vers-le-havre/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-le-havre/', destination: 'https://moverz.fr/rouen-vers-le-havre/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-caen', destination: 'https://moverz.fr/rouen-vers-caen/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-caen/', destination: 'https://moverz.fr/rouen-vers-caen/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-amiens', destination: 'https://moverz.fr/rouen-vers-amiens/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-amiens/', destination: 'https://moverz.fr/rouen-vers-amiens/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-lille', destination: 'https://moverz.fr/rouen-vers-lille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      { source: '/rouen-vers-lille/', destination: 'https://moverz.fr/rouen-vers-lille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-rouen.fr' }],
      },
      
      // ============================================
      // MONTPELLIER (devis-demenageur-montpellier.fr)
      // ============================================
      {
        source: '/',
        destination: 'https://moverz.fr/demenagement/montpellier/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }],
      },
      { source: '/quartiers-montpellier', destination: 'https://moverz.fr/quartiers-montpellier/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/quartiers-montpellier/', destination: 'https://moverz.fr/quartiers-montpellier/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/ecusson', destination: 'https://moverz.fr/montpellier/ecusson/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/ecusson/', destination: 'https://moverz.fr/montpellier/ecusson/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/antigone', destination: 'https://moverz.fr/montpellier/antigone/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/antigone/', destination: 'https://moverz.fr/montpellier/antigone/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/pres-arenes', destination: 'https://moverz.fr/montpellier/pres-arenes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/pres-arenes/', destination: 'https://moverz.fr/montpellier/pres-arenes/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/beaux-arts', destination: 'https://moverz.fr/montpellier/beaux-arts/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/beaux-arts/', destination: 'https://moverz.fr/montpellier/beaux-arts/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/port-marianne', destination: 'https://moverz.fr/montpellier/port-marianne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/port-marianne/', destination: 'https://moverz.fr/montpellier/port-marianne/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-paris', destination: 'https://moverz.fr/montpellier-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-paris/', destination: 'https://moverz.fr/montpellier-vers-paris/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-lyon', destination: 'https://moverz.fr/montpellier-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-lyon/', destination: 'https://moverz.fr/montpellier-vers-lyon/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-marseille', destination: 'https://moverz.fr/montpellier-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-marseille/', destination: 'https://moverz.fr/montpellier-vers-marseille/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-toulouse', destination: 'https://moverz.fr/montpellier-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      { source: '/montpellier-vers-toulouse/', destination: 'https://moverz.fr/montpellier-vers-toulouse/', permanent: true, has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }] },
      {
        source: '/blog/:path*',
        destination: 'https://moverz.fr/blog/:path*/',
        permanent: true,
        has: [{ type: 'host', value: 'devis-demenageur-montpellier.fr' }],
      },
    ];
  },
};

export default nextConfig;

